version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/dashboard"  
    schedule:
      interval: "weekly"
      time: "23:00"
      timezone: Europe/London
      labels:
      - "dependencies"
    open-pull-requests-limit: 10
      reviewers:
      - "mlabouardy"
      - "Azanul"
      - "AvineshTripathi"
      
